### PR TITLE
Sh/prg

### PR DESCRIPTION
**Pull request by susuhahnml**

### CODE REVIEW

**Comment by susuhahnml** [comment]
Wating to see how I can fix the imports issues.

**Comment by susuhahnml** [comment]
ready to merge @namcsi

**Comment by namcsi** [comment]
Looks good, merged in. Out of curiosity, why is `-r requirements.txt` instead of adding the requirements to `install_requires` in `setup.cfg`?

**Comment by susuhahnml** [comment]
@namcsi because they need to be installed from py.test since these versions are not fully published. I tried adding the url in the setup but I never managed. So this was a fix while the new versions are released.

**Pull request merged**
